#!/usr/bin/env bash

if [[ -x "$(which docker-machine)" && "$(uname -s)" == "FreeBSD" ]]; then
  # lazy load the docker environment for Freebsd

  function lazy_docker {
      local DOCKER_VM=docker1
      if [[ -z "$DOCKER_MACHINE_NAME" ]]; then
          # docker vm is uninitialized for environment
          if docker-machine env $DOCKER_VM &>/dev/null; then
              # try initializing environment
              eval $(docker-machine env $DOCKER_VM)
              $(which docker) $@
          else
              # can't initialize environment - is the docker vm down?
              if docker-machine start $DOCKER_VM; then
                  # docker vm was down
                  eval $(docker-machine env $DOCKER_VM)
                  $(which docker) $@
              else
                  # docker vm is borked
                  echo ""
              fi
          fi

      else
          # happy path
          $(which docker) $@
      fi
  }

  export -f lazy_docker

  alias docker=lazy_docker
fi


