#!/usr/bin/env bash
# add gitcompletion
# https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash

GIT_COMPLETION="$HOME/.local/git/git-completion.bash"
if [ -f "$GIT_COMPLETION" ]; then
  # File may not exist, so don't follow for shellcheck linting (SC1090).
  # shellcheck source=/dev/null
  source "$GIT_COMPLETION"
fi

# ========================================================= #
# git config                                                #
# ========================================================= #
# git alias:
alias g="git "
alias gf="git fetch"
alias gl="git log --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%ad @ %cr) %C(bold blue)<%an>%Creset' --graph --abbrev-commit --date=short"
alias go="git checkout "
alias god="git checkout develop && git pull upstream develop"
alias gs='git status'
alias gr='git reset'
alias gm="git merge "
alias ga="git add "
alias ga\.="git add . "
alias gd="git diff"
alias gb='git branch'

# start/pop
alias stash="git stash"
alias pop="git stash pop"

function ssh_checked_git {
  $(command -v ssh-add) -l | grep ssh/id_rsa &>/dev/null || ssh-add ~/.ssh/id_rsa
  $(which git) "$@"
}
export -f ssh_checked_git

# commit
alias gc="  git commit "
alias gcm=" git commit -m "
alias gca=" git commit --amend "
alias gcma="git commit --amend -m "
alias gim=" git add . && git commit -m"
alias gima="git add . && git commit --amend"

# push
alias gp='   ssh_checked_git push'
alias gpo='  gp origin'
alias gpom=' gp origin   master'
alias gpod=' gp origin   develop'
alias gpocb='gp origin   $(cb)'
alias gpu='  gp upstream'
alias gpum=' gp upstream master'
alias gpud=' gp upstream develop'
alias gpucb='gp upstream $(cb)'

# pull
alias gpl='   ssh_checked_git pull'
alias gplo='  gpl origin'
alias gplom=' gpl origin master'
alias gplod=' gpl origin develop'
alias gplocb='gpl origin $(cb)'
alias gplu='  gpl upstream'
alias gplum=' gpl upstream master'
alias gplud=' gpl upstream develop'
alias gplucb='gpl upstream $(cb)'

# move and remove
alias gmv="git mv "
alias grm="git rm "

# update index
#
# use git-lock from git-extras
#alias guiau=' git update-index --assume-unchanged'
#alias guinau='git update-index --no-assume-unchanged'

alias gcl="ssh_checked_git clone "
alias gfl="ssh_checked_git fetch && gl"

alias gpub='go gh-pages && gpog && go master && gm gh-pages && gpom && go gh-pages && gs'
alias ghUp="gh pr --remote upstream -s"

# ====================================== #
# git helpers: hub           #
# ====================================== #
#TWIG_COMPLETION=~/.twig/twig-completion.bash
#FLOW_COMPLETION=/usr/local/etc/bash_completion.d/git-flow-completion.bash
#
#for GIT_HELPER in $TWIG_COMPLETION $FLOW_COMPLETION; do
#  [[ -s $GIT_HELPER ]] && source $GIT_HELPER
#done

alias git=hub

# hub-functionality
alias gpr='  hub pull-request'
alias gprud='hub pull-request -b `remote-name upstream`\/`repo-name upstream`:develop -h `remote-name origin`\/`repo-name origin`:`cb`'

function ignore {
  echo "$1" >> .gitignore
}

function cb {
  git status | grep "On branch " | cut -c 11-
}
function remote-full {
  git remote -v | grep "$1" | head -n 1 | cut -d ':' -f 2 | cut -d '.' -f 1
}
function remote-name {
  remote-full "$1" | cut -d '/' -f 1
}
function repo-name {
  remote-full "$1" | cut -d '/' -f 2
}

# function gitmv {
#   mv $1 $2
#   git-mv $2 $1
# }
# export -f gitmv

alias gitTree='tree -I ./client/bower_components -I node_modules'
