#!/usr/bin/env bash

safe_path_add "/usr/local/cuda/bin"
export LD_LIBRARY_PATH="/usr/local/cuda/lib64:$LD_LIBRARY_PATH"

function GPULogoOff {
  local GPU_NUM="$1"
  GPU_BRIGHTNESS="$(nvidia-settings --query [gpu:$GPU_NUM]/GPULogoBrightness --terse 2>/dev/null)"
  if [ "$GPU_BRIGHTNESS" != "0" ] && [ "$GPU_BRIGHTNESS" != "" ]; then
    nvidia-settings --assign [gpu:$GPU_NUM]/GPULogoBrightness=0 1> /dev/null
  fi
}

if command -v nvidia-settings &> /dev/null ; then
  GPULogoOff 0
  GPULogoOff 1
  GPULogoOff 2
  GPULogoOff 3
fi


