#!/bin/bash
# WARNING - THIS SCRIPT IS INCREDIBLY SLOW
# ========================================
export SSH_ENV="$HOME/.ssh/environment"

function start_agent {
  local sshenv
  sshenv="${SSH_ENV:-}"

  echo "Initialising new SSH agent..."
  #shellcheck disable=SC2091
  $(command -v ssh-agent) | sed 's/^echo/#echo/' > "${sshenv}"
  echo succeeded
  chmod 600 "${sshenv}"
  # File may not exist, so don't follow for shellcheck linting (SC1090).
  # shellcheck source=/dev/null
  . "${sshenv}" > /dev/null
}

# Source SSH settings, if applicable
if [ -f "${SSH_ENV}" ]; then
  # File may not exist, so don't follow for shellcheck linting (SC1090).
  # shellcheck source=/dev/null
  . "${SSH_ENV:-}" > /dev/null
  agentpid="${SSH_AGENT_PID:-}"

  # make ssh-agent idempotent.
  if [ -n "${agentpid}" ]; then
    ps aux | awk '{print $2}' | grep "$agentpid" > /dev/null || {
      start_agent
      /usr/bin/ssh-add
    }
  fi
else
    start_agent
    /usr/bin/ssh-add
fi

# Fix SSH auth socket location so agent forwarding works with tmux
if test "${SSH_AUTH_SOCK:-}" ; then
  ln -sf "${SSH_AUTH_SOCK:-}" ~/.ssh/ssh_auth_sock
fi

# fun stuff:
# alias pong="ping -c 1 $(echoip | head -n 1 | tr -s ' ' | cut -d ':' -f 2)"

#function ssh_add_mosh {
#  for key in rsa ed25519; do
#    if [ -f $HOME/.ssh/id_$key ]; then
#      $(command -v ssh-add) -l | grep ssh/id_rsa &>/dev/null || ssh-add ~/.ssh/id_rsa
#    fi
#  done
#
#  $(which mosh) "$@"
#}
#export -f ssh_add_mosh
#alias mosh="ssh_add_mosh"


