#!/usr/bin/env bash

export PROMPT_INCL_USER=false
export PROMPT_USER_COLOR="${WHITE}"
export PROMPT_HOST_COLOR="${GREEN}"
export PROMPT_HOST_COLOR_GIT=""
export PROMPT_SEP_COLOR="${NORMAL}"
export PROMPT_PATH_COLOR="${YELLOW}"
export PROMPT_PATH_COLOR_GIT="${YELLOW}"
export PROMPT_BRANCH_COLOR_GIT="${CYAN}"

export GPU_LIGHTS_ON="nocheck"


