#!/usr/bin/env bash

COMMAND="$1"
TARGET="$2"
FLAG="$3"
SUS=super-user-spark

git submodule update --init --recursive

case $COMMAND in
  ""|"help"|"-h"|"--help")
    $SUS -h
    echo "running through ./run_sus. run_sus arguments are:"
    echo ""
    echo "  ./run_sus COMMAND [TARGET FLAG]"
    echo ""
    echo "- COMMAND is passed down to $SUS"
    echo "- TARGET (optional) and is one of bash|config|desktop|home|tools"
    echo "- FLAG (optional) requires a target and is passed down to $SUS"
    echo "    only one flag is currently supported"
    ;;
  *)
    case $TARGET in
      "bash"|"config"|"desktop"|"home"|"tools")
        $SUS $COMMAND $TARGET/spark.sus $FLAG
        ;;
      *"bash/"|*"config/"|*"desktop/"|*"home/"|*"tools/")
        $SUS $COMMAND ${TARGET}spark.sus $FLAG
        ;;
      "")
        $SUS $COMMAND    bash/spark.sus
        $SUS $COMMAND  config/spark.sus
        $SUS $COMMAND desktop/spark.sus
        $SUS $COMMAND    home/spark.sus
        $SUS $COMMAND   tools/spark.sus
        ;;
      *)
        echo "bad target. Leave empty or use one of: bash, config, desktop, home, tools"
        exit 1
        ;;
    esac
esac

