#!/bin/bash

# ========================= #
# Load "run-once" settings  #
# ========================= #
[[ ! -f ~/.bash/functions  ]] || source ~/.bash/functions

eval "$(fasd --init auto)"

safe_source /usr/local/etc/bash_completion

# ========================================================= #
# setup environments                                        #
# ========================================================= #
safe_source ~/.bash/colors

for SETTING in $(find ~/.bash -depth 1 -type l); do
  if echo "$SETTING" | grep -Ev "/(colors|load|git-aware-prompt)$" >/dev/null; then
    safe_source $SETTING
  fi
done

# ========================================================= #
# PATH Exports                                              #
# ========================================================= #
safe_path_add /bin
safe_path_add /sbin
safe_path_add /usr/bin
safe_path_add /usr/sbin
safe_path_add /usr/local/bin
safe_path_add /usr/local/sbin

