#!/usr/bin/env bash

# ========================= #
# Load "run-once" settings  #
# ========================= #

# File may not exist, so don't follow for shellcheck linting (SC1090).
# shellcheck source=/dev/null
[[ ! -f ~/.bash/functions  ]] || source ~/.bash/functions

eval "$(fasd --init auto)"

# ========================================================= #
# setup environments                                        #
# ========================================================= #
safe_source ~/.bash/colors

for SETTING in $(find ~/.bash -type l); do
  if echo "$SETTING" | grep -Ev "/(colors|load|git-aware-prompt|prompt)$" >/dev/null; then
    safe_source "$SETTING"
  fi
done

safe_source ~/.bash/prompt # must be last

# ========================================================= #
# PATH Exports                                              #
# ========================================================= #
safe_path_add /bin
safe_path_add /sbin
safe_path_add /usr/bin
safe_path_add /usr/sbin
safe_path_add /usr/local/bin
safe_path_add /usr/local/sbin

