#!/usr/bin/env bash

# Add rbenv to PATH for scripting. Make sure this is the last PATH variable change.
safe_path_add "$HOME/.rbenv/bin"

# command -v rbenv >/dev/null && eval "$(rbenv init -)"
if command -v rbenv >/dev/null; then
  export RBENV_SHELL=bash
  safe_path_add "/home/stites/.rbenv/shims"
  safe_source '/usr/lib/rbenv/libexec/../completions/rbenv.bash'
  nohup command rbenv rehash > /dev/null 2>&1 &
  rbenv() {
    local command
    command="$1"
    if [ "$#" -gt 0 ]; then
      shift
    fi

    case "$command" in
    rehash|shell|update|use)
      eval "$(rbenv "sh-$command" "$@")";;
    *)
      command rbenv "$command" "$@";;
    esac
  }
fi





