#!/bin/bash

# RBENV=$HOME/.rbenv
# safe_path_add "$RBENV/bin"
#test -s "$RBENV" && source "$RBENV"

# test ! -d $RBENV && echo "rbenv not detected" && continue;
#find -P  $HOME/.rvm -type d -maxdepth 3 -name bin | xargs -n 1 bash -c 'safe_path_add "$@"' _

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
safe_path_add "$HOME/.rvm/bin"
