#! /usr/bin/env bash

BASE_PS1="${BRIGHT_BLUE}@${BLUE}\h${NORMAL}#_${GREEN}\W${RESET} "
BASE_PS1="${BRIGHT_BLUE}@${BLUE}\h${NORMAL}|${GREEN}\W${RESET} "
BASE_PS1="${BRIGHT_BLUE}@${BLUE}\h${NORMAL}/>${GREEN}\W${RESET} "
BASE_PS1="${BRIGHT_BLUE}@${BLUE}\h${NORMAL}||${GREEN}\W${RESET} "
BASE_PS1="${BRIGHT_BLUE}@${BLUE}\h${NORMAL}<>${GREEN}\W${RESET} "
BASE_PS1="${BRIGHT_BLUE}@${BLUE}\h${NORMAL}::${GREEN}\W${RESET} "
#BASE_PS1="${BLUE}@\h${NORMAL}#_(${GREEN}\W${RESET}) "

if hash task 2>/dev/null; then
  PS1="$(task +in +PENDING count) $BASE_PS1"
else
  PS1="$BASE_PS1"
fi

