{ config, lib, pkgs, ... }:

{
  environment.systemPackages = [ pkgs.lm_sensors ];

  systemd.services.fancontrol = {
    description = "Start fancontrol, if configured";
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "simple";
      ExecStart = "${pkgs.lm_sensors}/sbin/fancontrol";
    };
  };

  environment.etc."fancontrol".text = let
    mintemp="20";
    maxtemp="70"; # critical zone is 100, 60 is... quite noisy
    cpu_avg_sensor = "temp7_input"; # seven is the ... average sensor?
  in ''
    # Configuration file generated by pwmconfig, changes will be lost
    INTERVAL=10
    DEVPATH=hwmon0=devices/platform/coretemp.0 hwmon4=devices/platform/system76
    DEVNAME=hwmon0=coretemp hwmon4=system76
    FCTEMPS=hwmon4/pwm1=hwmon0/${cpu_avg_sensor} hwmon4/pwm2=hwmon0/${cpu_avg_sensor}
    FCFANS=hwmon4/pwm1=hwmon4/fan1_input hwmon4/pwm2=hwmon4/fan2_input
    MINTEMP=hwmon4/pwm1=${mintemp} hwmon4/pwm2=${mintemp}
    MAXTEMP=hwmon4/pwm1=${maxtemp} hwmon4/pwm2=${maxtemp}
    MINSTART=hwmon4/pwm1=182 hwmon4/pwm2=220
    MINSTOP=hwmon4/pwm1=12 hwmon4/pwm2=10
  '';

  # OLD CONFIGURATION:
  # environment.etc."fancontrol".text = ''
  #   # Configuration file generated by pwmconfig, changes will be lost
  #   DEVPATH=hwmon0= hwmon4=devices/platform/system76
  #   DEVNAME=hwmon0=acpitz hwmon4=system76
  #   FCTEMPS=hwmon4/pwm2=hwmon0/temp1_input hwmon4/pwm1=hwmon0/temp1_input
  #   FCFANS=hwmon4/pwm2=hwmon4/fan2_input hwmon4/pwm1=hwmon4/fan1_input
  #   MINTEMP=hwmon4/pwm2=20 hwmon4/pwm1=20
  #   MAXTEMP=hwmon4/pwm2=60 hwmon4/pwm1=60
  #   MINSTART=hwmon4/pwm2=150 hwmon4/pwm1=150
  #   MINSTOP=hwmon4/pwm2=16 hwmon4/pwm1=100
  # '';
}
