#!/bin/bash

alias vimd="nvim --headless "
alias vimattach="nvim --servername VIM_SERVER --remote-tab "
alias visnippets="nvim ~/.config/nvim/snippets/haskell.snippets"

# Use https://github.com/rdnetto/powerline-hs
export POWERLINE_COMMAND=$HOME/.local/bin/powerline-hs
export POWERLINE_CONFIG_COMMAND=/bin/true
# source ~/.config/powerline ???

