#!/usr/bin/env bash

export PROMPT_HOST_COLOR="${BLUE}"
export PROMPT_HOST_COLOR_GIT=""
export PROMPT_SEP_COLOR="${NORMAL}"
export PROMPT_PATH_COLOR="${GREEN}"
export PROMPT_PATH_COLOR_GIT="${YELLOW}"


