#!/bin/bash

# ========================= #
# Load "run-once" settings  #
# ========================= #
[[ ! -f  ~/.bash_colors         ]] || source ~/.bash_colors
[[ ! -f  ~/git/cfg/init.d/udfs  ]] || source ~/git/cfg/init.d/udfs

eval "$(fasd --init auto)"

if [ -f /usr/local/etc/bash_completion ]; then
  . /usr/local/etc/bash_completion
fi

# ========================================================= #
# setup environments                                        #
# ========================================================= #
# TODO: rename spark->maven, npm->node
# TODO: re-add ssh

# for SETTING in python ruby npm spark tmux java; do
#   [[ ! -f ~/.bashrc_$SETTING  ]] || source ~/.bashrc_$SETTING
# done

# ========================================================= #
# PATH Exports                                              #
# ========================================================= #
safe_path_add /bin
safe_path_add /sbin
safe_path_add /usr/bin
safe_path_add /usr/sbin
safe_path_add /usr/local/bin
safe_path_add /usr/local/sbin

