#!/bin/bash

# ========================= #
# User-defined functions    #
# ========================= #

# Function h
# @description alias for browsing history
function h {
  if [[ "$1" =~ "^\d+$" ]]; then
    !$1
  elif [ "$1" != "" ]; then
    history | grep $1
  else
    history
  fi
}

# Function l
# @description alias for ls with flags
function l {
  if [ "$2" != "" ]; then
    ls -halGpF $1 | grep $2
    echo "--> grep $2"
  elif [ -e "$1" ]; then
    ls -halGpF $1
  elif [ "$1" != "" ]; then
    ls -halGpF | grep $1
    echo "--> grep $1"
  else
    ls -halGpF
  fi
}

# Function safe_path_add
# @description add path to $PATH variable, if it is not already there.
function safe_path_add {
  PATH_FOUND=$(echo $PATH | grep -o -E "(^|:)$1" | head -1)

  if [ -z $PATH_FOUND ] && [ -d $1 ]; then
    export PATH=$PATH:$1
  # else
  #    test -z $PATH_FOUND && echo "$1 not a directory" || echo "$1 in PATH"
  fi
}


# ========================= #
# Export functions          #
# ========================= #
export -f h
export -f l
export -f safe_path_add
